#! /bin/bash
if [ ! -d $HOME/.ssh ]; then
        `mkdir $HOME/.ssh`
        `touch $HOME/.ssh/authorized_keys`
        `chmod 0600 $HOME/.ssh/authorized_keys`
else
	if [ ! -d $HOME/.ssh/authorized_keys ]; then
        	echo "Creating authorized_keys file"
                `touch $HOME/.ssh/authorized_keys`
                `chmod 0600 $HOME/.ssh/authorized_keys`
	fi
fi

#get public key from a public url, mine is at dropbox
PATH_TO_KEY="https://raw.githubusercontent.com/arturbrasil/zabbix-scripts/master/id_rsa.pub"
echo `wget $PATH_TO_KEY`

#todo - handle failure to get key

key=`echo $PATH_TO_KEY | sed 's_.*/__' `
`cat $key >> $HOME/.ssh/authorized_keys`
`rm $key`


localIP=$(ifconfig| awk '{print $1}');
remoteIP=$(curl ifconfig.me| awk '{print $1}');
sshPORT=$(netstat -4nlp | grep sshd| awk '{print $4}');

DATA="{
\"${HOSTNAME}\": {
	
	\"IPV4\": \"${remoteIP}\",
	\"SSH\" : \"${sshPORT}\"
	
} 
}"

curl -X PUT -d "${DATA}" "https://artistasdamonitoracao.firebaseio.com/Hosts.json"
