{
 "title": "Mikrotiks",
 "tags": [ "mikrotiks" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "HW - MIKROTIK.*" },
   {
    "name": "interface",
    "label": "Interface",
    "query": "HW - MIKROTIK.$host.Interface - Trafego.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Problemas no $host",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": {
    "0": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "refId": "A",
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "Zabbix": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Fabricante - MIKROTIK" },
     "host": { "filter": "$host" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "/.*/" }
    }
   }
  },
  { "title": "Portas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$interface Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "repeat": "interface",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Status administrativo da porta (.*) $interface/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Ping ICMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "host" },
  {
   "title": "ICMP Ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Voltagem",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": { "filter": "Voltagem" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Health" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": { "filter": "Temperatura do Sistema" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Clientes PPPoE",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": { "filter": "Clientes PPPoE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "PROBLEMAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  { "title": "Tráfego", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Tráfego na $interface",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "repeat": "interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Tráfego de entrada da interface (.*) $interface/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Tráfego de saída da interface (.*) $interface/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Memória", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memória",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memoria" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memoria Total" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memoria" },
     "group": { "filter": "HW - MIKROTIK" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memoria Utilizada" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}